// let fruits=["mango","apple","guava"]
// for (let fruit of fruits){
//     console.log(fruit)
// }

// array accesss all Element


// push the array 
// let language=["HTML","CSS","JAVASCRIPTS"];
// language.push("pythom","java");
// console.log(language);

// pop deleted item

// let computerl=["HTML","CSS","JAVASCRIPTS"];
// computerl.pop();
// console.log(computerl);
// console.log(" computerl",  computerl);


// shift delect first 

// let colour=["red", "blue", "yellow"];
// colour.shift();
// console.log(colour)


// let colour=["red", "blue", "yellow"];
// colour.unshift("orange");
// console.log(colour)

// using slice to cut the array giving index number
// let color=["red", "blue", "yellow"];
// console.log(color)
// console.log(color.slice(1,2))

// using Splice  and replace the jaaavaaa
// let arr=["HTML","CSS","JAVASCRIPTS"];
// console.log(arr)
// arr.splice(2,1,"java");
// console.log(arr)

// ADD a array 
// let arr=["HTML","CSS","JAVASCRIPTS"];
// // console.log(arr)
// arr.splice(2,0,"java","python");
// console.log(arr)


// let search=["HTML","CSS","JAVASCRIPTS"];
 
// search.indexOf("CSS");
// console.log(search);




// for loop hW


// PRIME NUMBER 1 TO 10 loop

// for (let i=1; i<=10 i++){
//     if (i%2==0):
//     console.log()
// }


let i=1;
while(i<=10){
    console.log("number")
    i++;
}





